In [1]:
%run one.ipynb

In [2]:
dfa1

                 High        Low       Open      Close       Volume  Adj Close
Date
2011-01-03  15.154905  14.926927  14.926927  15.123874   94513392.0  15.123874
2011-01-04  15.169670  15.018018  15.155656  15.068068   72907020.0  15.068068
2011-01-05  15.273524  15.016266  15.016767  15.241992  101190708.0  15.241992
2011-01-06  15.476226  15.266517  15.282282  15.352853   82229688.0  15.352853
2011-01-07  15.471722  15.268519  15.413163  15.426426   83963952.0  15.426426
...               ...        ...        ...        ...          ...        ...
2014-12-24  27.014500  26.754999  26.941000  26.846500   14754000.0  26.846500
2014-12-26  27.162500  26.774500  26.846500  27.076000   22270000.0  27.076000
2014-12-29  27.196501  26.858000  27.025000  26.865499   44300000.0  26.865499
2014-12-30  26.892000  26.680500  26.747999  26.764000   20972000.0  26.764000
2014-12-31  26.920000  26.510000  26.886999  26.533001   24648000.0  26.533001

[1006 rows x 6 columns]

In [3]:
import talib as ta

In [4]:
OBV=ta.OBV(dfa1['Close'], dfa1['Volume'])
OBV

Date
2011-01-03    9.451339e+07
2011-01-04    2.160637e+07
2011-01-05    1.227971e+08
2011-01-06    2.050268e+08
2011-01-07    2.889907e+08
                  ...
2014-12-24    2.403581e+09
2014-12-26    2.425851e+09
2014-12-29    2.381551e+09
2014-12-30    2.360579e+09
2014-12-31    2.335931e+09
Length: 1006, dtype: float64

In [5]:
dfa1['OBV']=OBV
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV
Date,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08
...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09

In [6]:
import datetime
import pandas_datareader.data as web
import matplotlib.pyplot as plt

## Data For Average Calculation

In [7]:
start=datetime.datetime(2010,1,2)
end=datetime.datetime(2014,12,31)
google=web.DataReader('GOOGL','yahoo',start,end)
dfa1_all=google
dfa1_all

                 High        Low       Open      Close       Volume  Adj Close
Date
2010-01-04  15.753504  15.621622  15.689439  15.684434   78169752.0  15.684434
2010-01-05  15.711712  15.554054  15.695195  15.615365  120067812.0  15.615365
2010-01-06  15.662162  15.174174  15.662162  15.221722  158988852.0  15.221722
2010-01-07  15.265265  14.831081  15.250250  14.867367  256315428.0  14.867367
2010-01-08  15.096346  14.742492  14.814815  15.065566  188783028.0  15.065566
...               ...        ...        ...        ...          ...        ...
2014-12-24  27.014500  26.754999  26.941000  26.846500   14754000.0  26.846500
2014-12-26  27.162500  26.774500  26.846500  27.076000   22270000.0  27.076000
2014-12-29  27.196501  26.858000  27.025000  26.865499   44300000.0  26.865499
2014-12-30  26.892000  26.680500  26.747999  26.764000   20972000.0  26.764000
2014-12-31  26.920000  26.510000  26.886999  26.533001   24648000.0  26.533001

[1258 rows x 6 columns]

# TREND INDICATORS

## MA30

In [8]:
MA30=ta.MA(dfa1_all['Close'], timeperiod=30, matype=0)
MA30=MA30.loc['2011-01-03':'2014-12-31']
MA30=MA30.array
dfa1['MA30']=MA30

## MA50

In [9]:
MA50=ta.MA(dfa1_all['Close'], timeperiod=50, matype=0)
MA50=MA50.loc['2011-01-03':'2014-12-31']
MA50=MA50.array
dfa1['MA50']=MA50

## MA200

In [10]:
MA200=ta.MA(dfa1_all['Close'], timeperiod=200, matype=0)
MA200=MA200.loc['2011-01-03':'2014-12-31']
MA200=MA200.array
dfa1['MA200']=MA200

In [11]:
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200
Date,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965
...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640

## EMA30

In [12]:
EMA30=ta.EMA(dfa1_all['Close'], timeperiod=30)
EMA30=EMA30.loc['2011-01-03':'2014-12-31']
EMA30=EMA30.array
dfa1['EMA30']=EMA30
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30
Date,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,14.865644
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,14.878703
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,14.902141
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,14.931220
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,14.963168
...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,26.738534
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,26.760306
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,26.767093
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,26.766893
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,26.751803

## EMA50

In [13]:
EMA50=ta.EMA(dfa1_all['Close'], timeperiod=50)
EMA50=EMA50.loc['2011-01-03':'2014-12-31']
EMA50=EMA50.array
dfa1['EMA50']=EMA50
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30,EMA50
Date,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,14.865644,14.678320
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,14.878703,14.693604
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,14.902141,14.715110
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,14.931220,14.740119
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,14.963168,14.767033
...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,26.738534,27.134280
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,26.760306,27.131994
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,26.767093,27.121543
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,26.766893,27.107522
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,26.751803,27.084992

## EMA200

In [14]:
EMA200=ta.EMA(dfa1_all['Close'], timeperiod=200)
EMA200=EMA200.loc['2011-01-03':'2014-12-31']
EMA200=EMA200.array
dfa1['EMA200']=EMA200
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30,EMA50,EMA200
Date,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,14.865644,14.678320,13.807189
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,14.878703,14.693604,13.819735
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,14.902141,14.715110,13.833886
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,14.931220,14.740119,13.849001
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,14.963168,14.767033,13.864696
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,26.738534,27.134280,27.681484
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,26.760306,27.131994,27.675459
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,26.767093,27.121543,27.667400
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,26.766893,27.107522,27.658411
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,26.751803,27.084992,27.647213

## MACD

In [15]:
macd, macdsignal, macdhist = ta.MACD(dfa1_all['Close'], fastperiod=12, slowperiod=26, signalperiod=9)
MACD=macd.loc['2011-01-03':'2014-12-31']
MACD=MACD.array
dfa1['MACD']=MACD
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30,EMA50,EMA200,MACD
Date,,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,14.865644,14.678320,13.807189,0.083001
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,14.878703,14.693604,13.819735,0.084373
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,14.902141,14.715110,13.833886,0.098360
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,14.931220,14.740119,13.849001,0.117041
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,14.963168,14.767033,13.864696,0.136213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,26.738534,27.134280,27.681484,-0.275374
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,26.760306,27.131994,27.675459,-0.199023
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,26.767093,27.121543,27.667400,-0.153728
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,26.766893,27.107522,27.658411,-0.124585
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,26.751803,27.084992,27.647213,-0.118760

## PARABOLIC SAR

In [16]:
SAR=ta.SAR(dfa1_all['High'], dfa1_all['Low'], acceleration=0, maximum=0)
SAR=SAR.loc['2011-01-03':'2014-12-31']
SAR=SAR.array
dfa1['SAR']=SAR
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30,EMA50,EMA200,MACD,SAR
Date,,,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,14.865644,14.678320,13.807189,0.083001,10.851602
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,14.878703,14.693604,13.819735,0.084373,10.851602
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,14.902141,14.715110,13.833886,0.098360,10.851602
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,14.931220,14.740119,13.849001,0.117041,10.851602
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,14.963168,14.767033,13.864696,0.136213,10.851602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,26.738534,27.134280,27.681484,-0.275374,10.851602
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,26.760306,27.131994,27.675459,-0.199023,10.851602
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,26.767093,27.121543,27.667400,-0.153728,10.851602
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,26.766893,27.107522,27.658411,-0.124585,10.851602
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,26.751803,27.084992,27.647213,-0.118760,10.851602

# MOMENTUM

## AVERAGE DIRECTIONAL MOVEMENT INDEX(ADX)

In [17]:
ADX=ta.ADX(dfa1_all['High'], dfa1_all['Low'], dfa1_all['Close'], timeperiod=14)
ADX=ADX.loc['2011-01-03':'2014-12-31']
ADX=ADX.array
dfa1['ADX']=ADX
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30,EMA50,EMA200,MACD,SAR,ADX
Date,,,,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,14.865644,14.678320,13.807189,0.083001,10.851602,13.622259
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,14.878703,14.693604,13.819735,0.084373,10.851602,13.357207
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,14.902141,14.715110,13.833886,0.098360,10.851602,13.624007
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,14.931220,14.740119,13.849001,0.117041,10.851602,14.721557
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,14.963168,14.767033,13.864696,0.136213,10.851602,15.740710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,26.738534,27.134280,27.681484,-0.275374,10.851602,31.786966
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,26.760306,27.131994,27.675459,-0.199023,10.851602,29.888021
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,26.767093,27.121543,27.667400,-0.153728,10.851602,28.198732
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,26.766893,27.107522,27.658411,-0.124585,10.851602,26.190765
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,26.751803,27.084992,27.647213,-0.118760,10.851602,24.717738

In [18]:
plus_DMI = ta.PLUS_DM(dfa1_all['High'], dfa1_all['Low'], timeperiod=14)
minus_DMI= ta.MINUS_DM(dfa1_all['High'], dfa1_all['Low'], timeperiod=14)
plus_DMI=plus_DMI.loc['2011-01-03':'2014-12-31']
minus_DMI=minus_DMI.loc['2011-01-03':'2014-12-31']
plus_DMI=plus_DMI.array
minus_DMI=minus_DMI.array
dfa1['plus_DMI']=plus_DMI
dfa1['minus_DMI']=minus_DMI
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30,EMA50,EMA200,MACD,SAR,ADX,plus_DMI,minus_DMI
Date,,,,,,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,14.865644,14.678320,13.807189,0.083001,10.851602,13.622259,0.748328,0.626396
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,14.878703,14.693604,13.819735,0.084373,10.851602,13.357207,0.709640,0.581653
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,14.902141,14.715110,13.833886,0.098360,10.851602,13.624007,0.762806,0.540107
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,14.931220,14.740119,13.849001,0.117041,10.851602,14.721557,0.911021,0.501528
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,14.963168,14.767033,13.864696,0.136213,10.851602,15.740710,0.845948,0.465704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,26.738534,27.134280,27.681484,-0.275374,10.851602,31.786966,1.717424,1.691210
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,26.760306,27.131994,27.675459,-0.199023,10.851602,29.888021,1.742752,1.570410
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,26.767093,27.121543,27.667400,-0.153728,10.851602,28.198732,1.652270,1.458238
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,26.766893,27.107522,27.658411,-0.124585,10.851602,26.190765,1.534251,1.531577
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,26.751803,27.084992,27.647213,-0.118760,10.851602,24.717738,1.424661,1.592679

In [ ]:
def implement_adx_strategy(prices, pdi, ndi, adx):
    buy_price = []
    sell_price = []
    adx_signal = []
    signal = 0
    
    for i in range(len(prices)):
        if adx[i-1] < 25 and adx[i] > 25 and pdi[i] > ndi[i]:
            if signal != 1:
                buy_price.append(prices[i])
                sell_price.append(np.nan)
                signal = 1
                adx_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                adx_signal.append(0)
        elif adx[i-1] < 25 and adx[i] > 25 and ndi[i] > pdi[i]:
            if signal != -1:
                buy_price.append(np.nan)
                sell_price.append(prices[i])
                signal = -1
                adx_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                adx_signal.append(0)
        else:
            buy_price.append(np.nan)
            sell_price.append(np.nan)
            adx_signal.append(0)
            
    return buy_price, sell_price, adx_signal

buy_price, sell_price, adx_signal = implement_adx_strategy(aapl['close'], aapl['plus_di'], aapl['minus_di'], aapl['adx'])

## STOCHASTIC OSCILLATOR(STO)

In [19]:
dfa1.describe()

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30,EMA50,EMA200,MACD,SAR,ADX,plus_DMI,minus_DMI
count,1006.000000,1006.000000,1006.000000,1006.000000,1.006000e+03,1006.000000,1.006000e+03,1006.000000,1006.000000,1006.000000,1006.000000,1006.000000,1006.000000,1006.000000,1006.000000,1006.000000,1006.000000,1006.000000
mean,20.386885,20.052382,20.230720,20.223059,9.092822e+07,20.223059,9.921835e+08,20.055188,19.932549,18.792833,20.051481,19.920466,18.852881,0.083272,10.851602,25.026870,1.242810,1.202539
std,5.830638,5.757577,5.806299,5.794967,5.595801e+07,5.794967,1.204568e+09,5.742671,5.696480,5.215150,5.721467,5.664323,5.074848,0.313955,0.000000,8.973067,0.518335,0.604946
min,12.030781,11.837337,11.861862,11.883884,1.475400e+07,11.883884,-2.337656e+09,12.707041,12.964850,13.264135,12.675916,12.984464,13.688554,-0.745553,10.851602,9.075975,0.287696,0.314626
25%,15.302616,15.016704,15.158846,15.179742,5.946248e+07,15.179742,2.024933e+08,15.080906,15.045706,14.270033,15.130967,15.037551,14.378354,-0.152007,10.851602,18.131303,0.856415,0.784103
50%,18.899775,18.500375,18.603353,18.636761,8.198793e+07,18.636761,1.235100e+09,18.140107,17.787990,16.305540,17.975039,17.696774,16.547735,0.076738,10.851602,22.594049,1.178884,1.077585
75%,26.764458,26.292222,26.560996,26.535626,1.085164e+08,26.535626,2.082717e+09,26.735693,26.359122,22.874309,26.729267,26.189188,23.158288,0.324652,10.851602,31.115864,1.532372,1.438923
max,30.752752,30.495495,30.700701,30.534784,5.611863e+08,30.534784,2.728041e+09,30.090416,29.509860,28.764416,29.834463,29.400292,28.115430,1.025787,10.851602,48.249994,4.003965,3.933769

In [20]:
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30,EMA50,EMA200,MACD,SAR,ADX,plus_DMI,minus_DMI
Date,,,,,,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,14.865644,14.678320,13.807189,0.083001,10.851602,13.622259,0.748328,0.626396
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,14.878703,14.693604,13.819735,0.084373,10.851602,13.357207,0.709640,0.581653
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,14.902141,14.715110,13.833886,0.098360,10.851602,13.624007,0.762806,0.540107
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,14.931220,14.740119,13.849001,0.117041,10.851602,14.721557,0.911021,0.501528
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,14.963168,14.767033,13.864696,0.136213,10.851602,15.740710,0.845948,0.465704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,26.738534,27.134280,27.681484,-0.275374,10.851602,31.786966,1.717424,1.691210
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,26.760306,27.131994,27.675459,-0.199023,10.851602,29.888021,1.742752,1.570410
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,26.767093,27.121543,27.667400,-0.153728,10.851602,28.198732,1.652270,1.458238
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,26.766893,27.107522,27.658411,-0.124585,10.851602,26.190765,1.534251,1.531577
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,26.751803,27.084992,27.647213,-0.118760,10.851602,24.717738,1.424661,1.592679

In [21]:
fastk, fastd = ta.STOCHRSI(dfa1_all['Close'], timeperiod=14, fastk_period=5, fastd_period=3, fastd_matype=0)
K=fastk.loc['2011-01-03':'2014-12-31']
K=K.array
dfa1['%K']=K
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30,EMA50,EMA200,MACD,SAR,ADX,plus_DMI,minus_DMI,%K
Date,,,,,,,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,14.865644,14.678320,13.807189,0.083001,10.851602,13.622259,0.748328,0.626396,100.000000
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,14.878703,14.693604,13.819735,0.084373,10.851602,13.357207,0.709640,0.581653,74.130267
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,14.902141,14.715110,13.833886,0.098360,10.851602,13.624007,0.762806,0.540107,100.000000
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,14.931220,14.740119,13.849001,0.117041,10.851602,14.721557,0.911021,0.501528,100.000000
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,14.963168,14.767033,13.864696,0.136213,10.851602,15.740710,0.845948,0.465704,100.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,26.738534,27.134280,27.681484,-0.275374,10.851602,31.786966,1.717424,1.691210,92.559304
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,26.760306,27.131994,27.675459,-0.199023,10.851602,29.888021,1.742752,1.570410,100.000000
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,26.767093,27.121543,27.667400,-0.153728,10.851602,28.198732,1.652270,1.458238,44.734376
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,26.766893,27.107522,27.658411,-0.124585,10.851602,26.190765,1.534251,1.531577,0.000000
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,26.751803,27.084992,27.647213,-0.118760,10.851602,24.717738,1.424661,1.592679,0.000000

In [22]:
D=fastd.loc['2011-01-03':'2014-12-31']
D=D.array
dfa1['%D']=D
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30,EMA50,EMA200,MACD,SAR,ADX,plus_DMI,minus_DMI,%K,%D
Date,,,,,,,,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,14.865644,14.678320,13.807189,0.083001,10.851602,13.622259,0.748328,0.626396,100.000000,33.333333
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,14.878703,14.693604,13.819735,0.084373,10.851602,13.357207,0.709640,0.581653,74.130267,58.043422
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,14.902141,14.715110,13.833886,0.098360,10.851602,13.624007,0.762806,0.540107,100.000000,91.376756
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,14.931220,14.740119,13.849001,0.117041,10.851602,14.721557,0.911021,0.501528,100.000000,91.376756
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,14.963168,14.767033,13.864696,0.136213,10.851602,15.740710,0.845948,0.465704,100.000000,100.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,26.738534,27.134280,27.681484,-0.275374,10.851602,31.786966,1.717424,1.691210,92.559304,97.519768
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,26.760306,27.131994,27.675459,-0.199023,10.851602,29.888021,1.742752,1.570410,100.000000,97.519768
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,26.767093,27.121543,27.667400,-0.153728,10.851602,28.198732,1.652270,1.458238,44.734376,79.097893
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,26.766893,27.107522,27.658411,-0.124585,10.851602,26.190765,1.534251,1.531577,0.000000,48.244792
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,26.751803,27.084992,27.647213,-0.118760,10.851602,24.717738,1.424661,1.592679,0.000000,14.911459

In [23]:
type(dfa1['Close'])

pandas.core.series.Series

In [24]:
import numpy as np

In [25]:
def implement_stoch_strategy (a,b,c):    
    buy_price = []
    sell_price = []
    stoch_signal = []
    signal = 0

    for i in range(len(dfa1['Close'])):
        k=dfa1['%K']
        d=dfa1['%D']
        if k[i] < 20 and d[i] < 20 and k[i] < d[i]:
            if signal != 1:
                buy_price.append(dfa1['Close'][i])
                sell_price.append(np.nan)
                signal = 1
                stoch_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                stoch_signal.append(0)
        elif k[i] > 80 and d[i] > 80 and k[i] > d[i]:
            if signal != -1:
                buy_price.append(np.nan)
                sell_price.append(dfa1['Close'][i])
                signal = -1
                stoch_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                stoch_signal.append(0)
        else:
            buy_price.append(np.nan)
            sell_price.append(np.nan)
            stoch_signal.append(0)
            
    return buy_price, sell_price, stoch_signal
            
buy_price, sell_price, stoch_signal = implement_stoch_strategy(dfa1['Close'], dfa1['%K'], dfa1['%D'])
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,EMA30,EMA50,EMA200,MACD,SAR,ADX,plus_DMI,minus_DMI,%K,%D
Date,,,,,,,,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,14.865644,14.678320,13.807189,0.083001,10.851602,13.622259,0.748328,0.626396,100.000000,33.333333
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,14.878703,14.693604,13.819735,0.084373,10.851602,13.357207,0.709640,0.581653,74.130267,58.043422
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,14.902141,14.715110,13.833886,0.098360,10.851602,13.624007,0.762806,0.540107,100.000000,91.376756
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,14.931220,14.740119,13.849001,0.117041,10.851602,14.721557,0.911021,0.501528,100.000000,91.376756
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,14.963168,14.767033,13.864696,0.136213,10.851602,15.740710,0.845948,0.465704,100.000000,100.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,26.738534,27.134280,27.681484,-0.275374,10.851602,31.786966,1.717424,1.691210,92.559304,97.519768
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,26.760306,27.131994,27.675459,-0.199023,10.851602,29.888021,1.742752,1.570410,100.000000,97.519768
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,26.767093,27.121543,27.667400,-0.153728,10.851602,28.198732,1.652270,1.458238,44.734376,79.097893
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,26.766893,27.107522,27.658411,-0.124585,10.851602,26.190765,1.534251,1.531577,0.000000,48.244792
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,26.751803,27.084992,27.647213,-0.118760,10.851602,24.717738,1.424661,1.592679,0.000000,14.911459

In [26]:
stoch_signal

[0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 -1,
 0,
 0,
 0,
 1,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 1,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 -1,
 0,
 0,
 1,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

## RATE OF CHANGE

## RSI

In [27]:
RSI = ta.RSI(dfa1_all['Close'], timeperiod=14)
RSI=RSI.loc['2011-01-03':'2014-12-31']
RSI=RSI.array
dfa1['RSI']=RSI
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,...,EMA50,EMA200,MACD,SAR,ADX,plus_DMI,minus_DMI,%K,%D,RSI
Date,,,,,,,,,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,...,14.678320,13.807189,0.083001,10.851602,13.622259,0.748328,0.626396,100.000000,33.333333,58.136948
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,...,14.693604,13.819735,0.084373,10.851602,13.357207,0.709640,0.581653,74.130267,58.043422,56.008491
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,...,14.715110,13.833886,0.098360,10.851602,13.624007,0.762806,0.540107,100.000000,91.376756,60.822555
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,...,14.740119,13.849001,0.117041,10.851602,14.721557,0.911021,0.501528,100.000000,91.376756,63.559872
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,...,14.767033,13.864696,0.136213,10.851602,15.740710,0.845948,0.465704,100.000000,100.000000,65.293004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,...,27.134280,27.681484,-0.275374,10.851602,31.786966,1.717424,1.691210,92.559304,97.519768,52.113598
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,...,27.131994,27.675459,-0.199023,10.851602,29.888021,1.742752,1.570410,100.000000,97.519768,54.639064
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,...,27.121543,27.667400,-0.153728,10.851602,28.198732,1.652270,1.458238,44.734376,79.097893,51.933648
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,...,27.107522,27.658411,-0.124585,10.851602,26.190765,1.534251,1.531577,0.000000,48.244792,50.631832
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,...,27.084992,27.647213,-0.118760,10.851602,24.717738,1.424661,1.592679,0.000000,14.911459,47.701203

## CCI

In [28]:
CCI=ta.CCI(dfa1_all['High'], dfa1_all['Low'], dfa1_all['Close'], timeperiod=14)
CCI=CCI.loc['2011-01-03':'2014-12-31']
CCI=CCI.array
dfa1['CCI']=CCI
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,...,EMA200,MACD,SAR,ADX,plus_DMI,minus_DMI,%K,%D,RSI,CCI
Date,,,,,,,,,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,...,13.807189,0.083001,10.851602,13.622259,0.748328,0.626396,100.000000,33.333333,58.136948,61.562559
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,...,13.819735,0.084373,10.851602,13.357207,0.709640,0.581653,74.130267,58.043422,56.008491,63.704751
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,...,13.833886,0.098360,10.851602,13.624007,0.762806,0.540107,100.000000,91.376756,60.822555,111.022165
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,...,13.849001,0.117041,10.851602,14.721557,0.911021,0.501528,100.000000,91.376756,63.559872,209.632871
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,...,13.864696,0.136213,10.851602,15.740710,0.845948,0.465704,100.000000,100.000000,65.293004,187.574310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,...,27.681484,-0.275374,10.851602,31.786966,1.717424,1.691210,92.559304,97.519768,52.113598,90.430327
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,...,27.675459,-0.199023,10.851602,29.888021,1.742752,1.570410,100.000000,97.519768,54.639064,99.583010
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,...,27.667400,-0.153728,10.851602,28.198732,1.652270,1.458238,44.734376,79.097893,51.933648,86.402761
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,...,27.658411,-0.124585,10.851602,26.190765,1.534251,1.531577,0.000000,48.244792,50.631832,58.923856
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,...,27.647213,-0.118760,10.851602,24.717738,1.424661,1.592679,0.000000,14.911459,47.701203,42.446578

In [29]:
def implement_cci_strategy(a,b):
    buy_price = []
    sell_price = []
    cci_signal = []
    signal = 0
    cci=CCI
    
    lower_band = (-100)
    upper_band = 100
    
    for i in range(len(dfa1['Close'])):
        if cci[i-1] > lower_band and cci[i] < lower_band:
            if signal != 1:
                buy_price.append(dfa1['Close'][i])
                sell_price.append(np.nan)
                signal = 1
                cci_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                cci_signal.append(0)
                
        elif cci[i-1] < upper_band and cci[i] > upper_band:
            if signal != -1:
                buy_price.append(np.nan)
                sell_price.append(dfa1['Close'][i])
                signal = -1
                cci_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                cci_signal.append(0)
                
        else:
            buy_price.append(np.nan)
            sell_price.append(np.nan)
            cci_signal.append(0)
            
    return buy_price, sell_price, cci_signal

buy_price, sell_price, cci_signal = implement_cci_strategy(dfa1['Close'], dfa1['CCI'])
cci_signal

[0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]


# VOLATILITY

## ATR

## Historical Volatility

## Bollinger bands

In [30]:
upperband, middleband, lowerband = ta.BBANDS(dfa1_all['Close'], timeperiod=5, nbdevup=2, nbdevdn=2, matype=0)
upperband, middleband, lowerband=upperband, middleband, lowerband.loc['2011-01-03':'2014-12-31']
upperband, middleband, lowerband=upperband, middleband, lowerband.array
dfa1['upperband']=upperband
dfa1['middleband']=middleband
dfa1['lowerband']=lowerband
dfa1

,High,Low,Open,Close,Volume,Adj Close,OBV,MA30,MA50,MA200,...,ADX,plus_DMI,minus_DMI,%K,%D,RSI,CCI,upperband,middleband,lowerband
Date,,,,,,,,,,,,,,,,,,,,,
2011-01-03,15.154905,14.926927,14.926927,15.123874,94513392.0,15.123874,9.451339e+07,14.770137,14.993594,13.264135,...,13.622259,0.748328,0.626396,100.000000,33.333333,58.136948,61.562559,15.169589,15.000500,14.831412
2011-01-04,15.169670,15.018018,15.155656,15.068068,72907020.0,15.068068,2.160637e+07,14.779555,14.988383,13.269718,...,13.357207,0.709640,0.581653,74.130267,58.043422,56.008491,63.704751,15.192845,15.016516,14.840187
2011-01-05,15.273524,15.016266,15.016767,15.241992,101190708.0,15.241992,1.227971e+08,14.794444,14.984665,13.277235,...,13.624007,0.762806,0.540107,100.000000,91.376756,60.822555,111.022165,15.311455,15.056907,14.802358
2011-01-06,15.476226,15.266517,15.282282,15.352853,82229688.0,15.352853,2.050268e+08,14.819878,14.982112,13.284263,...,14.721557,0.911021,0.501528,100.000000,91.376756,63.559872,209.632871,15.460966,15.130180,14.799394
2011-01-07,15.471722,15.268519,15.413163,15.426426,83963952.0,15.426426,2.889907e+08,14.837788,14.982097,13.290965,...,15.740710,0.845948,0.465704,100.000000,100.000000,65.293004,187.574310,15.511723,15.242642,14.973562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,2.403581e+09,26.814800,27.107500,28.227696,...,31.786966,1.717424,1.691210,92.559304,97.519768,52.113598,90.430327,27.380747,26.426600,25.472454
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,2.425851e+09,26.786917,27.108290,28.214295,...,29.888021,1.742752,1.570410,100.000000,97.519768,54.639064,99.583010,27.451405,26.695600,25.939795
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,2.381551e+09,26.755033,27.108680,28.201876,...,28.198732,1.652270,1.458238,44.734376,79.097893,51.933648,86.402761,27.168582,26.868300,26.568018
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,2.360579e+09,26.721850,27.120990,28.186534,...,26.190765,1.534251,1.531577,0.000000,48.244792,50.631832,58.923856,27.107840,26.898100,26.688360
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,2.335931e+09,26.695217,27.119270,28.167640,...,24.717738,1.424661,1.592679,0.000000,14.911459,47.701203,42.446578,27.167734,26.817000,26.466266

In [31]:
def implement_bb_strategy(a,b,c):
    buy_price = []
    sell_price = []
    bb_signal = []
    signal = 0
    data=dfa1['Open']
    lower_bb=dfa1['lowerband']
    upper_bb=dfa1['upperband']
    
    for i in range(len(data)):
        if data[i-1] > lower_bb[i-1] and data[i] < lower_bb[i]:
            if signal != 1:
                buy_price.append(data[i])
                sell_price.append(np.nan)
                signal = 1
                bb_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                bb_signal.append(0)
        elif data[i-1] < upper_bb[i-1] and data[i] > upper_bb[i]:
            if signal != -1:
                buy_price.append(np.nan)
                sell_price.append(data[i])
                signal = -1
                bb_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                bb_signal.append(0)
        else:
            buy_price.append(np.nan)
            sell_price.append(np.nan)
            bb_signal.append(0)
            
    return buy_price, sell_price, bb_signal

buy_price, sell_price, bb_signal = implement_bb_strategy(dfa1['Close'], dfa1['lowerband'], dfa1['upperband'])

In [32]:
bb_signal

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 -1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]