In [3]:
import pandas as pd

In [59]:
df_amzn = pd.read_csv("C:\\Users\\Windows 11\\Documents\\project\\Project\\amzn_price.csv")
df_amp = pd.read_csv("C:\\Users\Windows 11\\Documents\\project\\Project\\AMP_price.csv")
df_cop = pd.read_csv("C:\\Users\Windows 11\\Documents\\project\\Project\\cop_price.csv")
df_goog = pd.read_csv("C:\\Users\\Windows 11\\Documents\\project\\Project\\goog_price.csv")
df_meta = pd.read_csv("C:\\Users\\Windows 11\\Documents\\project\\Project\\meta_price.csv")
df_nflx = pd.read_csv("C:\\Users\\Windows 11\\Documents\\project\\Project\\nflx_price.csv")
df_pxd = pd.read_csv("C:\\Users\\Windows 11\\Documents\\project\\Project\\pxd_price.csv")

In [60]:
df_amzn.drop(df_amzn.columns[[0,9,11,12,13]],axis=1,inplace=True)
df_amp.drop(df_amp.columns[[0,9,11,12,13]],axis=1,inplace=True)
df_cop.drop(df_cop.columns[[0,9,11,12,13]],axis=1,inplace=True)
df_goog.drop(df_goog.columns[[0,9,11,12,13]],axis=1,inplace=True)
df_meta.drop(df_meta.columns[[0,9,11,12,13]],axis=1,inplace=True)
df_nflx.drop(df_nflx.columns[[0,9,11,12,13]],axis=1,inplace=True)
df_pxd.drop(df_pxd.columns[[0,9,11,12,13]],axis=1,inplace=True)

In [109]:
dfo=df_goog
dfo

,ma30_50_signal,ma30_200_signal,ma50_200_signal,Obv_signal,sma100_signal,macd_signal,adx_signal,stoch_signal,rsi_signal,bb_signal,Close
0,1,1,1,1,1,1,1,1,0,0,27.724083
1,0,0,0,0,1,0,0,0,0,0,27.521841
2,0,0,0,0,1,0,0,0,0,0,27.828691
3,0,0,0,0,1,0,0,0,-1,0,28.365179
4,0,0,0,0,1,0,0,-1,0,0,28.424210
...,...,...,...,...,...,...,...,...,...,...,...
1002,0,0,0,0,1,0,0,1,0,0,53.006001
1003,0,0,0,0,1,0,0,0,0,0,52.837002
1004,0,0,0,0,1,0,0,0,0,0,52.468498
1005,0,0,0,-1,1,0,0,0,0,0,52.407001
1006,0,0,0,0,1,0,0,0,0,0,52.320000

In [110]:
sl1=dfo['ma30_50_signal']
sl2=dfo['ma30_200_signal']
sl3=dfo['ma50_200_signal']
sl4=dfo['Obv_signal']
sl5=dfo['sma100_signal']
sl6=dfo['macd_signal']
sl7=dfo['adx_signal']
sl8=dfo['stoch_signal']
sl9=dfo['rsi_signal']
sl10=dfo['bb_signal']

In [111]:
from scipy.optimize import NonlinearConstraint, Bounds, LinearConstraint

In [112]:
def const(p):
    w1,w2,w3,w4,w5,w6,w7,w8,w9,w10 = p
    return w1+w2+w3+w4+w5+w6+w7+w8+w9+w10

In [113]:
nlc = NonlinearConstraint(const, 1 ,1)

In [114]:
import sympy as sp

In [115]:
w1=sp.symbols('w1')
w2=sp.symbols('w2')
w3=sp.symbols('w3')
w4=sp.symbols('w4')
w5=sp.symbols('w5')
w6=sp.symbols('w6')
w7=sp.symbols('w7')
w8=sp.symbols('w8')
w9=sp.symbols('w9')
w10=sp.symbols('w10')

In [116]:
import numpy as np
from scipy.optimize import differential_evolution
from scipy.optimize import NonlinearConstraint, Bounds


bounds = [[0, 1], [0, 1],[0, 1], [0, 1],[0, 1], [0, 1],[0, 1], [0, 1],[0, 1], [0, 1]]

def func(p):
    w1,w2,w3,w4,w5,w6,w7,w8,w9,w10 = p
    mon=100000
    td=0.2
    amount=0
    for i in range(0,len(dfa1)):
        r = ((w1*sl1[i]+w2*sl2[i]+w3*sl3[i]+w4*sl4[i]+w5*sl5[i]+w6*sl6[i]+w7*sl7[i]+w8*sl8[i]+w9*sl9[i]+w10*sl10[i])/(w1+w2+w3+w4+w5+w6+w7+w8+w9+w10))
        if r>td:
            sumall=mon//dfo['Close'][i]
            amount+=sumall
            mon-=sumall*dfo['Close'][i]
        elif r<-td:
            mon+=amount*dfo['Close'][i]
            amount=0
        else:
            pass
    ret=mon+amount*df_amzn['Close'][len(dfa1)-1]
    return -ret

In [117]:
def fobj():
    result = differential_evolution(func, bounds,constraints=(nlc),maxiter=1000)
    print(result)

In [ ]:
fobj()

In [ ]:
df=pd.DataFrame({'GOOG' : [0.03322728, 0.17789633, 0.20643122, 0.04901172, 0.02944978,0.06280884, 0.01737008, 0.26118814, 0.03622071 , 0.12639588],
               'AMZN' :[0.05382357, 0.11597249, 0.16117411, 0.08293008, 0.06021601,0.14365769, 0.13546286, 0.07086823, 0.09617899, 0.07971599,-205290.52818679815],
               'COP' : [0.04707394, 0.04970202, 0.03905992, 0.03197686, 0.09107059,0.10481044, 0.07141184, 0.03220175, 0.38665312, 0.14603952],
               'PXD' : [0.27755385, 0.11776644, 0.10175624, 0.03502675, 0.05700024,0.08900609, 0.02204514, 0.23652257, 0.03600717, 0.0273155],
               'META' : [0.09740131, 0.35929012, 0.10281266, 0.02680168, 0.02492434,0.18874649, 0.06264384, 0.01266959, 0.0420342 , 0.08267577],
               'NFLX' : [0.06672124, 0.07114398, 0.02088772, 0.07240193, 0.11569577,0.02019018, 0.03425696, 0.54848935, 0.027285  , 0.02292786],
               'AMP' : [0.21954123, 0.0221416 , 0.00541483, 0.02188176, 0.02018149,0.06778772, 0.25096217, 0.2496707 , 0.03522765, 0.10719086]})