In [1]:
%run one.ipynb

In [2]:
import talib as ta
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
RSI = ta.RSI(dfa1['Close'])
dfa1['RSI']=RSI

MA30=ta.MA(dfa1['Close'], timeperiod=30)
dfa1['MA30']=MA30

MA50=ta.MA(dfa1['Close'], timeperiod=50, matype=0)
dfa1['MA50']=MA50

MA200=ta.MA(dfa1['Close'], timeperiod=200, matype=0)
dfa1['MA200']=MA200

macd, macdsignal, macdhist = ta.MACD(dfa1['Close'], fastperiod=12, slowperiod=26, signalperiod=9)
MACD=macd.loc['2011-01-03':'2014-12-31']
dfa1['MACD']=MACD
dfa1['macdsignal']=macdsignal
dfa1['macdhist']=macdhist

In [3]:
def implement_rsi_strategy(prices, data):    
    buy_price = []
    sell_price = []
    rsi_signal = []
    signal = 0

    for i in range(len(prices)):
        if prices[i] <= 35:
            if signal != 1:
                buy_price.append(prices[i])
                sell_price.append(np.nan)
                signal = 1
                rsi_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                rsi_signal.append(0)
        elif prices[i] >= 70:
            if signal != -1:
                buy_price.append(np.nan)
                sell_price.append(prices[i])
                signal = -1
                rsi_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                rsi_signal.append(0)
        else:
            buy_price.append(np.nan)
            sell_price.append(np.nan)
            rsi_signal.append(0)
            
    return buy_price, sell_price, rsi_signal
            
buy_price, sell_price, rsi_signal = implement_rsi_strategy(RSI, dfa1)

In [4]:
dfa1["rsi_signal"]=rsi_signal

In [5]:
def implement_ma_strategy(prices, data):    
    buy_price = []
    sell_price = []
    ma_signal = []
    signal = 0

    for i in range(len(data)):
        if data['MA50'][i] > data['MA200'][i]:
            if signal != 1:
                buy_price.append(prices[i])
                sell_price.append(np.nan)
                signal = 1
                ma_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                ma_signal.append(0)
        elif data['MA50'][i] < data['MA200'][i]:
            if signal != -1:
                buy_price.append(np.nan)
                sell_price.append(prices[i])
                signal = -1
                ma_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                ma_signal.append(0)
        else:
            buy_price.append(np.nan)
            sell_price.append(np.nan)
            ma_signal.append(0)
            
    return buy_price, sell_price, ma_signal
            
buy_price, sell_price, ma50_200_signal = implement_ma_strategy(dfa1['Open'], dfa1)

In [6]:
dfa1["ma50_200_signal"]=ma50_200_signal

In [7]:
def implement_ma_strategy(prices, data):    
    buy_price = []
    sell_price = []
    ma_signal = []
    signal = 0

    for i in range(len(data)):
        if data['MA30'][i] > data['MA50'][i]:
            if signal != 1:
                buy_price.append(prices[i])
                sell_price.append(np.nan)
                signal = 1
                ma_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                ma_signal.append(0)
        elif data['MA30'][i] < data['MA50'][i]:
            if signal != -1:
                buy_price.append(np.nan)
                sell_price.append(prices[i])
                signal = -1
                ma_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                ma_signal.append(0)
        else:
            buy_price.append(np.nan)
            sell_price.append(np.nan)
            ma_signal.append(0)
            
    return buy_price, sell_price, ma_signal
            
buy_price, sell_price, ma30_50_signal = implement_ma_strategy(dfa1['Open'], dfa1)

In [8]:
dfa1["ma30_50_signal"]=ma30_50_signal

,High,Low,Open,Close,Volume,Adj Close,RSI,MA30,MA50,MA200,MACD,macdsignal,macdhist,rsi_signal,ma50_200_signal,ma30_50_signal
Date,,,,,,,,,,,,,,,,
2010-01-04,15.753504,15.621622,15.689439,15.684434,78169752.0,15.684434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
2010-01-05,15.711712,15.554054,15.695195,15.615365,120067812.0,15.615365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
2010-01-06,15.662162,15.174174,15.662162,15.221722,158988852.0,15.221722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
2010-01-07,15.265265,14.831081,15.250250,14.867367,256315428.0,14.867367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
2010-01-08,15.096346,14.742492,14.814815,15.065566,188783028.0,15.065566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-24,27.014500,26.754999,26.941000,26.846500,14754000.0,26.846500,52.113598,26.814800,27.10750,28.227696,-0.275374,-0.396057,0.120682,0,0,0
2014-12-26,27.162500,26.774500,26.846500,27.076000,22270000.0,27.076000,54.639064,26.786917,27.10829,28.214295,-0.199023,-0.356650,0.157627,0,0,0
2014-12-29,27.196501,26.858000,27.025000,26.865499,44300000.0,26.865499,51.933648,26.755033,27.10868,28.201876,-0.153728,-0.316066,0.162337,0,0,0
2014-12-30,26.892000,26.680500,26.747999,26.764000,20972000.0,26.764000,50.631832,26.721850,27.12099,28.186534,-0.124585,-0.277770,0.153184,0,0,0
2014-12-31,26.920000,26.510000,26.886999,26.533001,24648000.0,26.533001,47.701203,26.695217,27.11927,28.167640,-0.118760,-0.245968,0.127207,0,0,0

In [9]:
def implement_ma_strategy(prices, data):    
    buy_price = []
    sell_price = []
    ma_signal = []
    signal = 0

    for i in range(len(data)):
        if data['MA30'][i] > data['MA200'][i]:
            if signal != 1:
                buy_price.append(prices[i])
                sell_price.append(np.nan)
                signal = 1
                ma_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                ma_signal.append(0)
        elif data['MA30'][i] < data['MA200'][i]:
            if signal != -1:
                buy_price.append(np.nan)
                sell_price.append(prices[i])
                signal = -1
                ma_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                ma_signal.append(0)
        else:
            buy_price.append(np.nan)
            sell_price.append(np.nan)
            ma_signal.append(0)
            
    return buy_price, sell_price, ma_signal
            
buy_price, sell_price, ma30_200_signal = implement_ma_strategy(dfa1['Open'], dfa1)

In [10]:
dfa1["ma30_200_signal"]=ma30_200_signal

In [11]:
def implement_ma_strategy(prices, data):    
    buy_price = []
    sell_price = []
    ma_signal = []
    signal = 0

    for i in range(len(data)):
        if data['MACD'][i] > data['macdsignal'][i]:
            if signal != 1:
                buy_price.append(prices[i])
                sell_price.append(np.nan)
                signal = 1
                ma_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                ma_signal.append(0)
        elif data['MACD'][i] < data['macdsignal'][i]:
            if signal != -1:
                buy_price.append(np.nan)
                sell_price.append(prices[i])
                signal = -1
                ma_signal.append(signal)
            else:
                buy_price.append(np.nan)
                sell_price.append(np.nan)
                ma_signal.append(0)
        else:
            buy_price.append(np.nan)
            sell_price.append(np.nan)
            ma_signal.append(0)
            
    return buy_price, sell_price, ma_signal
            
buy_price, sell_price, macd_signal = implement_ma_strategy(dfa1['Open'], dfa1)

In [12]:
dfa1["macd_signal"]=macd_signal

In [15]:
Sig_Sheet=dfa1.loc['2011-01-03':'2014-12-31'].loc[:,["rsi_signal","ma50_200_signal","ma30_50_signal","ma30_200_signal","macd_signal"]]
Sig_Sheet

,rsi_signal,ma50_200_signal,ma30_50_signal,ma30_200_signal,macd_signal
Date,,,,,
2011-01-03,0,0,0,0,1
2011-01-04,0,0,0,0,0
2011-01-05,0,0,0,0,0
2011-01-06,0,0,0,0,0
2011-01-07,0,0,0,0,0
...,...,...,...,...,...
2014-12-24,0,0,0,0,0
2014-12-26,0,0,0,0,0
2014-12-29,0,0,0,0,0
2014-12-30,0,0,0,0,0
2014-12-31,0,0,0,0,0